# Generated by Django 5.0 on 2025-05-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
